// Code generated by entc, DO NOT EDIT.

package recordfood

const (
	// Label holds the string label denoting the recordfood type in the database.
	Label = "record_food"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRecordID holds the string denoting the record_id field in the database.
	FieldRecordID = "record_id"
	// FieldFoodID holds the string denoting the food_id field in the database.
	FieldFoodID = "food_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// Table holds the table name of the recordfood in the database.
	Table = "record_foods"
)

// Columns holds all SQL columns for recordfood fields.
var Columns = []string{
	FieldID,
	FieldRecordID,
	FieldFoodID,
	FieldAmount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RecordIDValidator is a validator for the "record_id" field. It is called by the builders before save.
	RecordIDValidator func(int) error
	// FoodIDValidator is a validator for the "food_id" field. It is called by the builders before save.
	FoodIDValidator func(int) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(float64) error
)
