// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FoodsColumns holds the columns for the "foods" table.
	FoodsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "unit", Type: field.TypeString, Size: 50},
	}
	// FoodsTable holds the schema information for the "foods" table.
	FoodsTable = &schema.Table{
		Name:       "foods",
		Columns:    FoodsColumns,
		PrimaryKey: []*schema.Column{FoodsColumns[0]},
	}
	// RecordsColumns holds the columns for the "records" table.
	RecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_updated_at", Type: field.TypeTime},
	}
	// RecordsTable holds the schema information for the "records" table.
	RecordsTable = &schema.Table{
		Name:       "records",
		Columns:    RecordsColumns,
		PrimaryKey: []*schema.Column{RecordsColumns[0]},
	}
	// RecordFoodsColumns holds the columns for the "record_foods" table.
	RecordFoodsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "record_id", Type: field.TypeInt},
		{Name: "food_id", Type: field.TypeInt},
		{Name: "amount", Type: field.TypeInt, Default: 1},
	}
	// RecordFoodsTable holds the schema information for the "record_foods" table.
	RecordFoodsTable = &schema.Table{
		Name:       "record_foods",
		Columns:    RecordFoodsColumns,
		PrimaryKey: []*schema.Column{RecordFoodsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FoodsTable,
		RecordsTable,
		RecordFoodsTable,
	}
)

func init() {
}
