// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/haton14/ohagi-api/ent/migrate"

	"github.com/haton14/ohagi-api/ent/food"
	"github.com/haton14/ohagi-api/ent/record"
	"github.com/haton14/ohagi-api/ent/recordfood"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Food is the client for interacting with the Food builders.
	Food *FoodClient
	// Record is the client for interacting with the Record builders.
	Record *RecordClient
	// RecordFood is the client for interacting with the RecordFood builders.
	RecordFood *RecordFoodClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Food = NewFoodClient(c.config)
	c.Record = NewRecordClient(c.config)
	c.RecordFood = NewRecordFoodClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Food:       NewFoodClient(cfg),
		Record:     NewRecordClient(cfg),
		RecordFood: NewRecordFoodClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:     cfg,
		Food:       NewFoodClient(cfg),
		Record:     NewRecordClient(cfg),
		RecordFood: NewRecordFoodClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Food.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Food.Use(hooks...)
	c.Record.Use(hooks...)
	c.RecordFood.Use(hooks...)
}

// FoodClient is a client for the Food schema.
type FoodClient struct {
	config
}

// NewFoodClient returns a client for the Food from the given config.
func NewFoodClient(c config) *FoodClient {
	return &FoodClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `food.Hooks(f(g(h())))`.
func (c *FoodClient) Use(hooks ...Hook) {
	c.hooks.Food = append(c.hooks.Food, hooks...)
}

// Create returns a create builder for Food.
func (c *FoodClient) Create() *FoodCreate {
	mutation := newFoodMutation(c.config, OpCreate)
	return &FoodCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Food entities.
func (c *FoodClient) CreateBulk(builders ...*FoodCreate) *FoodCreateBulk {
	return &FoodCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Food.
func (c *FoodClient) Update() *FoodUpdate {
	mutation := newFoodMutation(c.config, OpUpdate)
	return &FoodUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FoodClient) UpdateOne(f *Food) *FoodUpdateOne {
	mutation := newFoodMutation(c.config, OpUpdateOne, withFood(f))
	return &FoodUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FoodClient) UpdateOneID(id int) *FoodUpdateOne {
	mutation := newFoodMutation(c.config, OpUpdateOne, withFoodID(id))
	return &FoodUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Food.
func (c *FoodClient) Delete() *FoodDelete {
	mutation := newFoodMutation(c.config, OpDelete)
	return &FoodDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *FoodClient) DeleteOne(f *Food) *FoodDeleteOne {
	return c.DeleteOneID(f.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *FoodClient) DeleteOneID(id int) *FoodDeleteOne {
	builder := c.Delete().Where(food.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FoodDeleteOne{builder}
}

// Query returns a query builder for Food.
func (c *FoodClient) Query() *FoodQuery {
	return &FoodQuery{
		config: c.config,
	}
}

// Get returns a Food entity by its id.
func (c *FoodClient) Get(ctx context.Context, id int) (*Food, error) {
	return c.Query().Where(food.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FoodClient) GetX(ctx context.Context, id int) *Food {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FoodClient) Hooks() []Hook {
	return c.hooks.Food
}

// RecordClient is a client for the Record schema.
type RecordClient struct {
	config
}

// NewRecordClient returns a client for the Record from the given config.
func NewRecordClient(c config) *RecordClient {
	return &RecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `record.Hooks(f(g(h())))`.
func (c *RecordClient) Use(hooks ...Hook) {
	c.hooks.Record = append(c.hooks.Record, hooks...)
}

// Create returns a create builder for Record.
func (c *RecordClient) Create() *RecordCreate {
	mutation := newRecordMutation(c.config, OpCreate)
	return &RecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Record entities.
func (c *RecordClient) CreateBulk(builders ...*RecordCreate) *RecordCreateBulk {
	return &RecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Record.
func (c *RecordClient) Update() *RecordUpdate {
	mutation := newRecordMutation(c.config, OpUpdate)
	return &RecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecordClient) UpdateOne(r *Record) *RecordUpdateOne {
	mutation := newRecordMutation(c.config, OpUpdateOne, withRecord(r))
	return &RecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecordClient) UpdateOneID(id int) *RecordUpdateOne {
	mutation := newRecordMutation(c.config, OpUpdateOne, withRecordID(id))
	return &RecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Record.
func (c *RecordClient) Delete() *RecordDelete {
	mutation := newRecordMutation(c.config, OpDelete)
	return &RecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RecordClient) DeleteOne(r *Record) *RecordDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RecordClient) DeleteOneID(id int) *RecordDeleteOne {
	builder := c.Delete().Where(record.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecordDeleteOne{builder}
}

// Query returns a query builder for Record.
func (c *RecordClient) Query() *RecordQuery {
	return &RecordQuery{
		config: c.config,
	}
}

// Get returns a Record entity by its id.
func (c *RecordClient) Get(ctx context.Context, id int) (*Record, error) {
	return c.Query().Where(record.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecordClient) GetX(ctx context.Context, id int) *Record {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RecordClient) Hooks() []Hook {
	return c.hooks.Record
}

// RecordFoodClient is a client for the RecordFood schema.
type RecordFoodClient struct {
	config
}

// NewRecordFoodClient returns a client for the RecordFood from the given config.
func NewRecordFoodClient(c config) *RecordFoodClient {
	return &RecordFoodClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `recordfood.Hooks(f(g(h())))`.
func (c *RecordFoodClient) Use(hooks ...Hook) {
	c.hooks.RecordFood = append(c.hooks.RecordFood, hooks...)
}

// Create returns a create builder for RecordFood.
func (c *RecordFoodClient) Create() *RecordFoodCreate {
	mutation := newRecordFoodMutation(c.config, OpCreate)
	return &RecordFoodCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RecordFood entities.
func (c *RecordFoodClient) CreateBulk(builders ...*RecordFoodCreate) *RecordFoodCreateBulk {
	return &RecordFoodCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RecordFood.
func (c *RecordFoodClient) Update() *RecordFoodUpdate {
	mutation := newRecordFoodMutation(c.config, OpUpdate)
	return &RecordFoodUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecordFoodClient) UpdateOne(rf *RecordFood) *RecordFoodUpdateOne {
	mutation := newRecordFoodMutation(c.config, OpUpdateOne, withRecordFood(rf))
	return &RecordFoodUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecordFoodClient) UpdateOneID(id int) *RecordFoodUpdateOne {
	mutation := newRecordFoodMutation(c.config, OpUpdateOne, withRecordFoodID(id))
	return &RecordFoodUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RecordFood.
func (c *RecordFoodClient) Delete() *RecordFoodDelete {
	mutation := newRecordFoodMutation(c.config, OpDelete)
	return &RecordFoodDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RecordFoodClient) DeleteOne(rf *RecordFood) *RecordFoodDeleteOne {
	return c.DeleteOneID(rf.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RecordFoodClient) DeleteOneID(id int) *RecordFoodDeleteOne {
	builder := c.Delete().Where(recordfood.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecordFoodDeleteOne{builder}
}

// Query returns a query builder for RecordFood.
func (c *RecordFoodClient) Query() *RecordFoodQuery {
	return &RecordFoodQuery{
		config: c.config,
	}
}

// Get returns a RecordFood entity by its id.
func (c *RecordFoodClient) Get(ctx context.Context, id int) (*RecordFood, error) {
	return c.Query().Where(recordfood.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecordFoodClient) GetX(ctx context.Context, id int) *RecordFood {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RecordFoodClient) Hooks() []Hook {
	return c.hooks.RecordFood
}
