// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/haton14/ohagi-api/ent/food"
	"github.com/haton14/ohagi-api/ent/record"
	"github.com/haton14/ohagi-api/ent/recordfood"
	"github.com/haton14/ohagi-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	foodFields := schema.Food{}.Fields()
	_ = foodFields
	// foodDescName is the schema descriptor for name field.
	foodDescName := foodFields[0].Descriptor()
	// food.NameValidator is a validator for the "name" field. It is called by the builders before save.
	food.NameValidator = foodDescName.Validators[0].(func(string) error)
	// foodDescUnit is the schema descriptor for unit field.
	foodDescUnit := foodFields[1].Descriptor()
	// food.UnitValidator is a validator for the "unit" field. It is called by the builders before save.
	food.UnitValidator = foodDescUnit.Validators[0].(func(string) error)
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescCreatedAt is the schema descriptor for created_at field.
	recordDescCreatedAt := recordFields[0].Descriptor()
	// record.DefaultCreatedAt holds the default value on creation for the created_at field.
	record.DefaultCreatedAt = recordDescCreatedAt.Default.(func() time.Time)
	// recordDescLastUpdatedAt is the schema descriptor for last_updated_at field.
	recordDescLastUpdatedAt := recordFields[1].Descriptor()
	// record.DefaultLastUpdatedAt holds the default value on creation for the last_updated_at field.
	record.DefaultLastUpdatedAt = recordDescLastUpdatedAt.Default.(func() time.Time)
	recordfoodFields := schema.RecordFood{}.Fields()
	_ = recordfoodFields
	// recordfoodDescRecordID is the schema descriptor for record_id field.
	recordfoodDescRecordID := recordfoodFields[0].Descriptor()
	// recordfood.RecordIDValidator is a validator for the "record_id" field. It is called by the builders before save.
	recordfood.RecordIDValidator = recordfoodDescRecordID.Validators[0].(func(int) error)
	// recordfoodDescFoodID is the schema descriptor for food_id field.
	recordfoodDescFoodID := recordfoodFields[1].Descriptor()
	// recordfood.FoodIDValidator is a validator for the "food_id" field. It is called by the builders before save.
	recordfood.FoodIDValidator = recordfoodDescFoodID.Validators[0].(func(int) error)
	// recordfoodDescAmount is the schema descriptor for amount field.
	recordfoodDescAmount := recordfoodFields[2].Descriptor()
	// recordfood.DefaultAmount holds the default value on creation for the amount field.
	recordfood.DefaultAmount = recordfoodDescAmount.Default.(float64)
	// recordfood.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	recordfood.AmountValidator = recordfoodDescAmount.Validators[0].(func(float64) error)
}
