// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Food is the predicate function for food builders.
type Food func(*sql.Selector)

// Record is the predicate function for record builders.
type Record func(*sql.Selector)

// RecordFood is the predicate function for recordfood builders.
type RecordFood func(*sql.Selector)
